"""Public MOLEG-API interface."""

from .errors import (
    AmbiguousLawError,
    MolegApiError,
    NoResultError,
    ParseFailureError,
    SourceApiError,
    UnsupportedFormatError,
)
from .laws import MolegApi
from .models import (
    AdministrativeRuleArticleText,
    AdministrativeRuleHit,
    AdministrativeRuleIdentity,
    AdministrativeRuleText,
    ArticleText,
    DelegatedRule,
    DelegationGraph,
    HistoryEvent,
    InterpretationHit,
    InterpretationIdentity,
    InterpretationText,
    JudicialDecisionHit,
    JudicialDecisionIdentity,
    JudicialDecisionText,
    LawDiff,
    LawDiffChange,
    LawHit,
    LawHistory,
    LawIdentity,
    LawText,
)
from .source import LawGoKrClient

__all__ = [
    "AmbiguousLawError",
    "AdministrativeRuleArticleText",
    "AdministrativeRuleHit",
    "AdministrativeRuleIdentity",
    "AdministrativeRuleText",
    "ArticleText",
    "DelegatedRule",
    "DelegationGraph",
    "HistoryEvent",
    "InterpretationHit",
    "InterpretationIdentity",
    "InterpretationText",
    "JudicialDecisionHit",
    "JudicialDecisionIdentity",
    "JudicialDecisionText",
    "LawGoKrClient",
    "LawDiff",
    "LawDiffChange",
    "LawHit",
    "LawHistory",
    "LawIdentity",
    "LawText",
    "MolegApi",
    "MolegApiError",
    "NoResultError",
    "ParseFailureError",
    "SourceApiError",
    "UnsupportedFormatError",
]
