from __future__ import annotations

from dataclasses import dataclass, replace
import re
from typing import Any

from ..errors import (
    AmbiguousLawError,
    AsOfBeforeCoverageError,
    MolegApiError,
    NoResultError,
    ParseFailureError,
    SourceApiError,
    UnsupportedFormatError,
)
from ..models import (
    AdministrativeRuleHit,
    AdministrativeRuleArticleText,
    AdministrativeRuleContext,
    AdministrativeRuleIdentity,
    AdministrativeRuleText,
    Ambiguity,
    AnnexFormSource,
    AnnexFormHit,
    AnnexFormIdentity,
    AnnexFormText,
    AnnexSearchScope,
    AnnexType,
    ArticleContext,
    ArticleText,
    AuthorityContext,
    Basis,
    BundleBudget,
    BundleMode,
    BundleRequest,
    CandidateContext,
    CaseCourt,
    ContextGap,
    DeferredLookup,
    DelegationGraph,
    FollowUpSearch,
    HistoryEvent,
    InterpretationHit,
    InterpretationIdentity,
    InterpretationSearchSource,
    InterpretationText,
    JudicialDecisionHit,
    JudicialDecisionIdentity,
    JudicialDecisionText,
    LegalArticleCandidate,
    LegalContextBundle,
    LegalLawCandidate,
    LegalQueryExpansion,
    LegalTermCandidate,
    LoadedContext,
    LawDiff,
    LawHit,
    LawHistory,
    LawIdentity,
    LawStructure,
    LawStructureNode,
    LawText,
    LawToc,
    LawTocEntry,
    RevisionReason,
    StructuredTableData,
)
from ..normalization import (
    compact_date,
    compact_promulgation_number,
    extract_administrative_rule_articles,
    extract_articles,
    extract_supplementary_provisions,
    format_article_jo,
    normalize_administrative_rule_identity,
    normalize_annex_form_identity,
    normalize_article,
    normalize_delegated_rules,
    normalize_diff_changes,
    normalize_history_events,
    normalize_interpretation_identity,
    normalize_interpretation_text,
    normalize_judicial_decision_identity,
    normalize_judicial_decision_text,
    normalize_law_structure,
    normalize_law_identity,
    normalize_related_article_candidate,
    normalize_related_law_candidate,
    normalize_term_candidate,
    parse_law_history_html,
    parse_law_history_total_count,
    unwrap_search_administrative_rules,
    unwrap_search_interpretations,
    unwrap_search_judicial_decisions,
    unwrap_search_laws,
    unwrap_service_payload,
    unwrap_target_rows,
)
from ..source import LawGoKrClient, MolegSource

__all__ = [name for name in globals() if not name.startswith("__")]
